FROM ubuntu:18.04

## Set Not Interactive
ENV DEBIAN_FRONTEND=noninteractive

## Set a default Zone info to America/New_York
RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime

## Install core tools and dependencies
RUN apt-get -y update \
    && apt-get install -y software-properties-common build-essential \
    autoconf git-core git openssl libreadline7 libreadline-dev curl \
    zlib1g zlib1g-dev libssl1.0-dev libyaml-dev libsqlite3-dev sqlite3 \
    libxml2-dev libxslt-dev libmariadbclient-dev libpq-dev imagemagick \
    phantomjs libffi-dev vim g++-7 zip tzdata wget \
    && dpkg-reconfigure --frontend noninteractive tzdata \
    && rm -rf /var/lib/apt/lists/*

## Install i386 library
RUN dpkg --add-architecture i386 \
    && apt-get update && apt-get install -y libc6:i386 libstdc++6:i386 \
    && rm -rf /var/lib/apt/lists/*

## Create a link to our version of g++
RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 20

## Install ruby 2.7.4
RUN curl -L http://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.4.tar.gz > ruby-2.7.4.tar.gz \
    && tar -xvzf ruby-2.7.4.tar.gz && rm ruby-2.7.4.tar.gz \
    && cd ruby-2.7.4 \
    && ./configure --prefix=/usr/local --enable-shared \
    && make \
    && make install

# Install base gems
RUN gem install bundler -v 2.2.26 \
    && gem install "rubygems-update" --no-document \
    && gem install rb-inotify -v 0.10.1 --no-document\
    && gem install rice -v 2.2.0 --no-document \
    && gem install rubygems-bundler rake-compiler \
    && gem update --system '3.1.6'

# Install NodeJS 12
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - \
    && apt-get update \
    && apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/*

#Install YARN
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update \
    && apt-get install yarn \
    && rm -rf /var/lib/apt/lists/*


